# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: true
  allowed_methods_listener: true

  body_listener:
    enabled: true

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  #    routing_loader: true

  view:
    view_response_listener: true

  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { path: ^/admin, prefer_extension: true, fallback_format: html, priorities: [ html, json ] }
      - { path: ^/tests, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html, json ] }
