sonata_admin:
  title: 'Ryde Backend'
  title_logo: /img/ryde_ja.png
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
  assets:
    extra_stylesheets: [ 'css/custom-theme.css' ]

sonata_block:
  blocks:
    # enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]