#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#app.swagger_ui:
#  path: /api/doc
#  methods: GET
#  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger_ui:
  path: /doc/{area}
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: api }

sonata_user_admin_security:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

sonata_user_admin_resetting:
  resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
  prefix: /admin/resetting